### PR TITLE
✏️ Write a first draft of a 2024 Venue CFP

### PR DESCRIPTION
**Pull request by drewbrew**
Copied and pasted from last year's with:

- Updated dates
- Added gluten-free to the catering options

### CODE REVIEW

**Comment by jefftriplett** [comment]
I think we get fewer and fewer groups biting each year and this is a fairly daunting ask. It might be worth us cutting it down and getting some feedback from the NC folk while it's still fresh in their minds.

**Comment by PeterGrand** [comment]
I can say that we who did the Durham proposal felt like it was a LOT to compile. Even at the end I wasn't sure we had what would be considered a complete proposal. Lowering the bar at least for initial proposals seems wise to me.

**Comment by tim-schilling** [comment]
@PeterGrand would you be able to identify which of the items that you felt were a lot of work to compile, but are lesser benefits to DEFNA? That seems like a good list to remove or mark as "nice to haves".

**Comment by PeterGrand** [comment]
Yes, but it will have to be an after hours task hopefully tonight.

**Comment by PeterGrand** [comment]
OK I made a PR against this branch with my suggested edits: https://github.com/DEFNA/defna.org/pull/49

**Comment by drewbrew** [comment]
Closing this and we can revisit for 2025

**Pull request closed without merging**
