### PR TITLE
Update our board members.

### PR DESCRIPTION
**Pull request by tim-schilling**
- Adds Nicole to our board
- Moves Aaron to past board members
- Includes short blog post about the change

### CODE REVIEW

**Comment by tim-schilling** [comment]
That's a neat github action

**Comment by jefftriplett** [comment]
This is probably a good excuse to update everyone on our officer position changes from our recent election too?

**Comment by tim-schilling** [comment]
Good call.

**Comment by tim-schilling** [comment]
Updated

**Review by jefftriplett — APPROVED** [review]
LGTM

**Pull request merged**
