### PR TITLE
:pencil: Board Update 2020

### PR DESCRIPTION
**Pull request by jefftriplett**
Needs: 

- [x] blog post
- [ ] 2020 logos

### CODE REVIEW

**Review by KatherineMichel — APPROVED** [review]

**Comment by KatherineMichel** [comment]
@jefftriplett LGTM. Sorry for the delay in approving. I fixed a few dates, but didn't see any other problems. I'm planning to update my personal bio, but can do that at a later time.

**Comment by KatherineMichel** [comment]
@jefftriplett Oops, just realized its a WIP. Perhaps I should rescind my approval.

**Comment by jefftriplett** [comment]
@KatherineMichel thanks for catching the dates. I just marked a WIP to prevent an accidental merge. I'll push it out tonight or tomorrow.

**Comment by jefftriplett** [comment]
Merging, we'll sort it out later given our traffic levels.

**Pull request merged**
